{
 "title": "Gateway Data",
 "tags": [
  "mtnmesh",
  "gateway"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gateway",
    "label": "Gateway",
    "query": {
     "query": "from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (exists r[\"gateway_id\"]))\n  |> keep(columns: [\"gateway_id\"])\n  |> distinct(column: \"gateway_id\")\n  |> group()"
    }
   },
   {
    "name": "nodes",
    "label": "Nodes",
    "query": {
     "query": "import \"contrib/bonitoo-io/hex\"\nimport \"strings\"\n\nfrom(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"gateway_id\"] == \"${gateway}\")\n  |> filter(fn: (r) => r[\"_from\"] != string(v: hex.int(v: strings.trimPrefix(v: \"${gateway}\", prefix: \"!\"))))\n  |> keep(columns: [\"_time\", \"_from\", \"long_name\", \"short_name\"])\n  |> map(fn: (r) => ({ r with __value: string(v: r._from) + \":\" + string(v: r.long_name) + \" (\" + string(v: r.short_name) + \" / \" + string(v: r._from) + \")\" }))\n  |> group(columns: [\"__value\"])\n  |> last(column: \"_time\")\n  |> group()"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node RX SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_snr\")\n  |> filter(fn: (r) => r[\"gateway_id\"] == \"${gateway}\")\n  |> filter(fn: (r) => if length(arr: ${nodes:json}) == 0 then true else contains(value: r._from, set: ${nodes:json}))\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> map(fn: (r) => ({r with id: r.gateway_id + \"_\" + r._from} ))\n  |> group(columns: [\"_field\", \"gateway_id\", \"_from\", \"id\"])\n  |> movingAverage(n: 5)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> rename(columns: {_value: \"snr\"})"
    }
   ]
  },
  {
   "title": "Node RX RSSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_rssi\")\n  |> filter(fn: (r) => r[\"gateway_id\"] == \"${gateway}\")\n  |> filter(fn: (r) => if length(arr: ${nodes:json}) == 0 then true else contains(value: r._from, set: ${nodes:json}))\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> map(fn: (r) => ({r with id: r.gateway_id + \"_\" + r._from} ))\n  |> group(columns: [\"_field\", \"gateway_id\", \"_from\", \"id\"])\n  |> movingAverage(n: 5)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> rename(columns: {_value: \"snr\"})"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] != \"modelinfo\")\n  |> filter(fn: (r) => if length(arr: ${nodes:json}) == 0 then true else contains(value: r._from, set: ${nodes:json}))\n  |> filter(fn: (r) => r[\"gateway_id\"] == \"${gateway}\")\n  |> drop(columns: [\"_value\"])\n  |> group(columns: [\"_from\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false, column: \"_measurement\")"
    }
   ]
  },
  {
   "title": "Recent Packets",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] != \"modelinfo\")\n  |> filter(fn: (r) => r[\"gateway_id\"] == \"${gateway}\")\n  |> keep(columns: [\"_time\", \"_measurement\", \"_from\"])\n  |> group(columns: [\"_measurement\", \"_from\", \"_time\"])\n  |> last(column: \"_from\")\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> top(n: 6)\n  |> rename(columns: {_time: \"Time\", _from: \"Node ID\", _measurement: \"Packet Type\"})"
    }
   ]
  },
  { "title": "SNR", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "$nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "repeat": "nodes",
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_snr\")\n  |> filter(fn: (r) => r[\"gateway_id\"] == \"${gateway}\")\n  |> filter(fn: (r) => r[\"_from\"] == \"${nodes}\")\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> map(fn: (r) => ({r with id: r.gateway_id + \"_\" + r._from} ))\n  |> group(columns: [\"_field\", \"gateway_id\", \"_from\", \"id\"])\n  |> movingAverage(n: 5)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> rename(columns: {_value: \"snr\"})"
    }
   ]
  }
 ]
}