{
 "title": "MtnMesh",
 "tags": [
  "mtnmesh",
  "global"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   {
    "name": "nodes",
    "label": "Nodes",
    "query": {
     "query": "from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> keep(columns: [\"_time\", \"_from\", \"long_name\", \"short_name\"])\n  |> map(fn: (r) => ({ r with __value: string(v: r._from) + \":\" + string(v: r.long_name) + \" (\" + string(v: r.short_name) + \" / \" + string(v: r._from) + \")\" }))\n  |> group(columns: [\"__value\"])\n  |> last(column: \"_time\")\n  |> group()"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Count",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meshtastic\")\n  |> range(start: 0) // All time\n  |> filter(fn: (r) => r._measurement == \"node\")\n  |> keep(columns: [\"_from\"])\n  |> group()\n  |> distinct(column: \"_from\")\n  |> count()\n  |> rename(columns: {_value: \"All Time\"})"
    },
    {
     "query": "from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop) // All time\n  |> filter(fn: (r) => r._measurement == \"node\")\n  |> keep(columns: [\"_from\"])\n  |> group()\n  |> distinct(column: \"_from\")\n  |> count()\n  |> rename(columns: {_value: \"Selected Range\"})"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "import \"join\"\n\nmodels = from(bucket: \"meshtastic\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"modelinfo\")\n  |> group(columns: [\"displayName\"])\n  |> distinct()\n  |> group()\n\nnodes = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with hw_model: int(v: r.hw_model)}))\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"channel_id\", \"gateway_id\", \"to\"])\n  |> filter(fn: (r) => if length(arr: [${nodes:doublequote}]) == 0 then true else contains(value: r._from, set: [${nodes:doublequote}]))\n  |> group(columns: [\"_from\"])\n  |> last(column: \"_from\")\n  |> group()\n\njoin.left(\n  left: nodes,\n  right: models,\n  on: (l, r) => l.hw_model == r._value,\n  as: (l, r) => ({l with model: if exists r.displayName then r.displayName  else \"Unknown\"})\n) |> sort(columns: [\"hw_model\"])"
    }
   ]
  },
  {
   "title": "Model Breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"join\"\n\nmodels = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => exists r[\"hw_model\"])\n  |> keep(columns: [\"_from\", \"hw_model\"])\n  |> group(columns: [\"hw_model\"])\n  |> distinct(column: \"_from\")\n  |> count()\n  |> group()\n  |> map(fn: (r) => ({r with \"hw_model\": int(v: r.hw_model)}))\n\nmodelinfo = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"modelinfo\")\n  |> last()\n  |> group()\n\njoin.left(\n  left: models,\n  right: modelinfo,\n  on: (l, r) => l.hw_model == r._value,\n  as: (l, r) => ({l with \"model_name\": if exists r.displayName then r.displayName else \"Unknown: \" + string(v: l.hw_model)})\n)\n  |> keep(columns: [\"model_name\", \"_value\"])"
    }
   ]
  },
  {
   "title": "Latest Node Locations",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "// Query for position data\npositionData = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"position\")\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude_i\" or r[\"_field\"] == \"longitude_i\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n      r with \n      latitude: float(v: r.latitude_i) / 10000000.0, \n      longitude: float(v: r.longitude_i) / 10000000.0,\n      _from: string(v: r._from) // Ensure _from is treated as a string\n  }))\n  |> group(columns: [\"_from\"]) // Group by _from to get the latest position for each node\n  |> sort(columns: [\"_time\"], desc: true) // Sort the data by time in descending order\n  |> top(n: 1, columns: [\"_time\"]) // Get the top entry for each group\n  |> drop(columns: [\"_start\", \"_stop\", \"_measurement\", \"latitude_i\", \"longitude_i\"])\n\n// Query for node data\nnodeData = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> keep(columns: [\"_from\", \"short_name\"])\n  |> map(fn: (r) => ({\n      r with\n      _from: string(v: r._from) // Ensure _from is treated as a string\n  }))\n  |> group(columns: [\"_from\"]) // Group by _from to match the position data\n  |> sort(columns: [\"_time\"], desc: true) // Sort the data by time in descending order\n  |> top(n: 1, columns: [\"_time\"]) // Get the top entry for each group\n\n// Join position and node data on _from field\njoinedData = join(\n  tables: {pos: positionData, node: nodeData},\n  on: [\"_from\"]\n)\n  |> map(fn: (r) => ({\n      r with\n      short_name: r[\"short_name\"],\n      latitude: r[\"latitude\"],\n      longitude: r[\"longitude\"]\n  }))\n  |> drop(columns: [\"_time\", \"_value\", \"latitude_i\", \"longitude_i\"])\n\n// Final result for the map\njoinedData\n  |> keep(columns: [\"latitude\", \"longitude\", \"short_name\"])\n"
    }
   ]
  },
  {
   "title": "Network Activity",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "import \"experimental/geo\"\nimport \"join\"\n\n// Query for position data\npositionData = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"position\")\n  |> filter(fn: (r) => r[\"_field\"] == \"latitude_i\" or r[\"_field\"] == \"longitude_i\")\n  |> map(fn: (r) => ({r with _value: float(v: r._value) / 10000000.0}))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> geo.shapeData(latField: \"latitude_i\", lonField: \"longitude_i\", level: 13)\n  |> group()\n\n\ncellCounts = positionData\n  |> group(columns: [\"s2_cell_id\", \"_measurement\"])\n  |> duplicate(column: \"s2_cell_id\", as: \"cell_count\")\n  |> count(column: \"cell_count\")\n  |> map(fn: (r) => ({r with cell_count: float(v: r.cell_count)}))\n  |> group()\n\n\nmin = cellCounts\n  |> min(column: \"cell_count\")\n  |> findRecord(fn: (key) => true, idx: 0)\n\nmax = cellCounts\n  |> max(column: \"cell_count\")\n  |> findRecord(fn: (key) => true, idx: 0)\n\ncellWeight = cellCounts\n  |> map(fn: (r) => ({\n    r with weight: float(v: (r.cell_count - min.cell_count) / (max.cell_count - min.cell_count))\n  }))\n\njoined = join.left(\n  left: positionData,\n  right: cellWeight,\n  on: (l, r) => (l.s2_cell_id == r.s2_cell_id),\n  as: (l , r) => ({l with weight: r.weight})\n)\n\njoined"
    }
   ]
  },
  { "title": "Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Air Utilization TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"join\"\n\nair = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"air_util_tx\")\n  |> filter(fn: (r) => r[\"_value\"] < 200 and r[\"_value\"] >= 0)\n  |> filter(fn: (r) => if length(arr: [${nodes:doublequote}]) == 0 then true else contains(value: r._from, set: [${nodes:doublequote}]))\n  |> group(columns: [\"_from\"])\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n  \n\nnodes = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> drop(columns: [\"_field\", \"_value\", \"_start\", \"_stop\", \"to\", \"channel_id\"])\n  |> group(columns: [\"_from\", \"short_name\", \"long_name\"])\n  |> last(column: \"_from\")\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n\n\njoined = join.left(\n    left: air,\n    right: nodes,\n    on: (l, r) => l.id == r.id,\n    as: (l, r) => ({l with short_name: r.short_name, long_name: r.long_name})\n  )\n\njoined\n  |> group(columns: [\"_measurement\", \"_field\", \"id\", \"short_name\", \"long_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Channel Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"join\"\n\nchannel = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"channel_utilization\")\n  |> filter(fn: (r) => if length(arr: [${nodes:doublequote}]) == 0 then true else contains(value: r._from, set: [${nodes:doublequote}]))\n  |> group(columns: [\"_from\"])\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n\nnodes = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> drop(columns: [\"_field\", \"_value\", \"_start\", \"_stop\", \"to\", \"channel_id\"])\n  |> group(columns: [\"_from\", \"short_name\", \"long_name\"])\n  |> last(column: \"_from\")\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n\njoined = join.left(\n    left: channel,\n    right: nodes,\n    on: (l, r) => l.id == r.id,\n    as: (l, r) => ({l with short_name: r.short_name, long_name: r.long_name})\n  )\n\njoined\n  |> group(columns: [\"_measurement\", \"_field\", \"id\", \"short_name\", \"long_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n"
    },
    {
     "query": "import \"join\"\n\nchannel = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"channel_utilization\")\n  |> group(columns: [\"_from\"])\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n\nnodes = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> drop(columns: [\"_field\", \"_value\", \"_start\", \"_stop\", \"to\", \"channel_id\"])\n  |> group(columns: [\"_from\", \"short_name\", \"long_name\"])\n  |> last(column: \"_from\")\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n\njoined = join.left(\n    left: channel,\n    right: nodes,\n    on: (l, r) => l.id == r.id,\n    as: (l, r) => ({l with short_name: r.short_name, long_name: r.long_name})\n  )\n\nmoving_average_series = joined\n  |> group()  // Remove all grouping to calculate a global moving average\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 5)\n  |> map(fn: (r) => ({r with _field: \"Moving Average\", short_name: \"Overall Average\"}))  // Set a custom short_name\n\nmoving_average_series\n"
    }
   ]
  },
  { "title": "Temperature", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "import \"join\"\n\nhumidity = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"relative_humidity\")\n  |> filter(fn: (r) => (r[\"_value\"] >= 0) and (r[\"_value\"] <= 100))\n  |> filter(fn: (r) => if length(arr: [${nodes:doublequote}]) == 0 then true else contains(value: r._from, set: [${nodes:doublequote}]))\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n  \n\nnodes = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> drop(columns: [\"_field\", \"_value\", \"_start\", \"_stop\", \"to\", \"channel_id\"])\n  |> group(columns: [\"_from\", \"short_name\", \"long_name\"])\n  |> last(column: \"_from\")\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n\n\njoined = join.left(\n    left: humidity,\n    right: nodes,\n    on: (l, r) => l.id == r.id,\n    as: (l, r) => ({l with short_name: r.short_name, long_name: r.long_name})\n  )\n\njoined\n  |> group(columns: [\"_measurement\", \"_field\", \"id\", \"short_name\", \"long_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 5)"
    },
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather.openweathermap\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Battery Voltages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "import \"join\"\n\nvolts = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\n  |> group(columns: [\"_measurement\", \"_field\", \"_from\"])\n  |> filter(fn: (r) => if length(arr: [${nodes:doublequote}]) == 0 then true else contains(value: r._from, set: [${nodes:doublequote}]))\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n  \nnodes = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> drop(columns: [\"_field\", \"_value\", \"_start\", \"_stop\", \"to\", \"channel_id\"])\n  |> group(columns: [\"_from\", \"short_name\", \"long_name\"])\n  |> last(column: \"_from\")\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n\n  joined = join.left(\n    left: volts,\n    right: nodes,\n    on: (l, r) => l.id == r.id,\n    as: (l, r) => ({l with short_name: r.short_name, long_name: r.long_name, display_name: if exists r.short_name then r.short_name else l.id})\n  )\n\njoined\n  |> group(columns: [\"_measurement\", \"_field\", \"id\", \"short_name\", \"long_name\", \"display_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 5)"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"join\"\n\nbattery = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery\")\n  |> filter(fn: (r) => r[\"_field\"] == \"battery_level\")\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> filter(fn: (r) => if length(arr: [${nodes:doublequote}]) == 0 then true else contains(value: r._from, set: [${nodes:doublequote}]))\n  |> group(columns: [\"_from\", \"_field\"])\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n\nnodes = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> drop(columns: [\"_field\", \"_value\", \"_start\", \"_stop\", \"to\", \"channel_id\"])\n  |> group(columns: [\"_from\", \"short_name\", \"long_name\"])\n  |> last(column: \"_from\")\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n\njoined = join.left(\n    left: battery,\n    right: nodes,\n    on: (l, r) => l.id == r.id,\n    as: (l, r) => ({l with short_name: r.short_name, long_name: r.long_name})\n  )\n\njoined\n  |> group(columns: [\"_measurement\", \"_field\", \"id\", \"short_name\", \"long_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 4)"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "import \"join\"\n\nuptime = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery\")\n  |> filter(fn: (r) => r[\"_field\"] == \"uptime_seconds\")\n  |> filter(fn: (r) => r[\"_value\"] > 0 and r[\"_value\"] < 31536000)\n  |> filter(fn: (r) => if length(arr: [${nodes:doublequote}]) == 0 then true else contains(value: r._from, set: [${nodes:doublequote}]))\n  |> group()\n\nnodes = from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> drop(columns: [\"_field\", \"_value\", \"_start\", \"_stop\", \"to\", \"channel_id\"])\n  |> group(columns: [\"_from\", \"short_name\", \"long_name\"])\n  |> last(column: \"_from\")\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n\njoin.left(\n    left: uptime,\n    right: nodes,\n    on: (l, r) => l._from == r.id,\n    as: (l, r) => ({l with short_name: r.short_name, long_name: r.long_name, display_name: if exists r.short_name then r.short_name else l._from})\n  )\n  |> group(columns: [\"_measurement\", \"_field\", \"id\", \"short_name\", \"long_name\", \"display_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Roles",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "import \"dict\"\n\nroleNameDict = [\n    0: \"CLIENT\",\n    1: \"CLIENT_MUTE\",\n    2: \"ROUTER\",\n    3: \"ROUTER_CLIENT\",\n    4: \"REPEATER\",\n    5: \"TRACKER\",\n    6: \"SENSOR\",\n    7: \"TAK\",\n    8: \"CLIENT_HIDDEN\",\n    9: \"LOST_AND_FOUND\",\n    10: \"TAK_TRACKER\"\n]\n\nnodes = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"packet_id\")\n  |> filter(fn: (r) => if length(arr: [${nodes:doublequote}]) == 0 then true else contains(value: r._from, set: [${nodes:doublequote}]))\n\nnodesOther = nodes\n  |> filter(fn: (r) => exists r[\"role\"])\n\nnodesClient = nodes\n  |> filter(fn: (r) => not exists r[\"role\"])\n  |> set(key: \"role\", value: \"0\")\n\nunion(tables: [nodesOther, nodesClient])\n  |> map(fn: (r) => ({r with role_name: dict.get(dict: roleNameDict, key: int(v: r.role), default: \"UNKNOWN\")}))\n  |> group()\n  |> unique(column: \"_from\")\n  |> keep(columns: [\"short_name\", \"role\", \"role_name\"])\n"
    }
   ]
  },
  { "title": "MQTT Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Contributing Gateways",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"join\"\nimport \"strings\"\nimport \"contrib/bonitoo-io/hex\"\n\nhexify = (str) => {\n  hexString = hex.string(v: int(v: str))\n  return if strings.strlen(v: hexString) == 7 then \"0\" + hexString else hexString\n}\n\ngatewayIds = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> group(columns: [\"gateway_id\"])\n  |> count()\n  |> group()\n\nnodeIds = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> keep(columns: [\"_time\", \"_from\", \"short_name\", \"long_name\"])\n  |> group()\n  |> sort(columns: [\"_time\"], desc: true)\n  |> unique(column: \"_from\")\n  |> drop(columns: [\"_time\"])\n  |> map(fn: (r) => ({r with hex_id: \"!\" + hexify(str: r[\"_from\"])}))\n\njoinedData = join.left(\n  left: gatewayIds,\n  right: nodeIds,\n  on: (l, r) => l.gateway_id == r.hex_id,\n  as: (l, r) => ({r with hex_id: l.gateway_id, packets: l._value})\n)\n\njoinedData\n  |> map(fn: (r) => ({\n    r with\n    name: if exists r.short_name then r.short_name else r.hex_id\n  }))\n  |> filter(fn: (r) => r[\"name\"] !=  \"\")\n  |> keep(columns: [\"name\", \"packets\"])"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 16, "x": 8, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] != \"modelinfo\")\n  |> filter(fn: (r) => if length(arr: [${nodes:doublequote}]) == 0 then true else contains(value: r._from, set: [${nodes:doublequote}]))\n  |> drop(columns: [\"_value\"])\n  |> group(columns: [\"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false, column: \"_from\")"
    }
   ]
  }
 ]
}