{
 "title": "Individual Node",
 "description": "Information about an individual node as seen by the gateways (or a specific gateway) in the mesh. Select the node from the \"Nodes\" dropdown menu. If you want to view that nodes data as seen through a specific gateway then select that gateway as well.",
 "tags": [
  "node",
  "mtnmesh"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gateway",
    "label": "Gateway",
    "query": {
     "query": "from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => (exists r[\"gateway_id\"]))\n  |> keep(columns: [\"gateway_id\"])\n  |> distinct(column: \"gateway_id\")\n  |> group()"
    }
   },
   {
    "name": "nodes",
    "label": "Node",
    "query": {
     "query": "from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> keep(columns: [\"_time\", \"_from\", \"long_name\", \"short_name\"])\n  |> map(fn: (r) => ({ r with __value: string(v: r._from) + \":\" + string(v: r.long_name) + \" (\" + string(v: r.short_name) + \" / \" + string(v: r._from) + \")\" }))\n  |> group(columns: [\"__value\"])\n  |> last(column: \"_time\")\n  |> group()"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Info",
   "type": "stat",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"join\"\nimport \"strings\"\nimport \"contrib/bonitoo-io/hex\"\n\nhexify = (str) => {\n  hexString = hex.string(v: int(v: str))\n  return if strings.strlen(v: hexString) == 7 then \"0\" + hexString else hexString\n}\n\nmodels = from(bucket: \"meshtastic\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"modelinfo\")\n  |> group(columns: [\"displayName\"])\n  |> distinct()\n  |> group()\n\nnodes = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({r with hw_model: int(v: r.hw_model)}))\n  |> filter(fn: (r) => r._from == \"${nodes}\")\n  |> group(columns: [\"_from\"])\n  |> last(column: \"_from\")\n  |> group()\n\njoin.left(\n  left: nodes,\n  right: models,\n  on: (l, r) => r._value == l.hw_model,\n  as: (l, r) => ({l with model: if exists r.displayName then r.displayName  else \"Unknown\"})\n)\n  |> keep(columns: [\"short_name\", \"long_name\", \"model\", \"_from\"])\n  |> map(fn: (r) => ({r with \"Hex\": \"!\" + hexify(str: r._from)}))\n  |> rename(columns: {_from: \"ID\", short_name: \"Name Short\", long_name: \"Name Long\", model: \"Model\"})"
    },
    {
     "global_query_id": "list-records",
     "source": "url",
     "type": "global",
     "url": "https://github.com/grafana/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Neighbors Seen",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"neighbor\")\n  |> filter(fn: (r) => r[\"_from\"] == \"${nodes}\")\n  |> group(columns: [\"_field\", \"_from\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false, column: \"neighbor_id\")\n  |> rename(columns: {neighbor_id: \"_value\"})\n  |> movingAverage(n: 10)\n  |> group()"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"battery\" and r._field == \"uptime_seconds\")\n  |> filter(fn: (r) => r._from == \"${nodes}\")\n  |> filter(fn: (r) => if length(arr: ${gateway:json}) == 0 then true else contains(value: r.gateway_id, set: ${gateway:json}))"
    }
   ]
  },
  { "title": "Temperature", "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "import \"join\"\n\nhumidity = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"relative_humidity\")\n  |> filter(fn: (r) => r[\"_from\"] == string(v: ${nodes}))\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n  \n\nnodes = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"node\")\n  |> drop(columns: [\"_field\", \"_value\", \"_start\", \"_stop\", \"to\", \"channel_id\"])\n  |> group(columns: [\"_from\", \"short_name\", \"long_name\"])\n  |> last(column: \"_from\")\n  |> rename(columns: {_from: \"id\"})\n  |> group()\n\n\njoined = join.left(\n    left: humidity,\n    right: nodes,\n    on: (l, r) => l.id == r.id,\n    as: (l, r) => ({l with short_name: r.short_name, long_name: r.long_name})\n  )\n\njoined\n  |> group(columns: [\"_measurement\", \"_field\", \"id\", \"short_name\", \"long_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 5)"
    },
    {
     "query": "from(bucket: \"weather\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weather.openweathermap\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Node RX SNR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "rxSnr = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_snr\")\n  |> filter(fn: (r) => if length(arr: ${gateway:json}) == 0 then true else contains(value: r.gateway_id, set: ${gateway:json}))\n  |> filter(fn: (r) => r[\"_from\"] == \"${nodes}\")\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> group(columns: [\"_from\", \"_field\"])\n\nrxSnr\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 10)\n  |> rename(columns: {_value: \"snr_mean\"})\n  |> yield(name: \"mean\")\n\nrxSnr\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n  |> movingAverage(n: 10)\n  |> rename(columns: {_value: \"snr_min\"})\n  |> yield(name: \"min\")\n\nrxSnr\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> movingAverage(n: 10)\n  |> rename(columns: {_value: \"snr_max\"})\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Node RX RSSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "rxSnr = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"rx_rssi\")\n  |> filter(fn: (r) => if length(arr: ${gateway:json}) == 0 then true else contains(value: r.gateway_id, set: ${gateway:json}))\n  |> filter(fn: (r) => r[\"_from\"] == \"${nodes}\")\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> group(columns: [\"_from\", \"_field\"])\n\nrxSnr\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 10)\n  |> rename(columns: {_value: \"snr_mean\"})\n  |> yield(name: \"mean\")\n\nrxSnr\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n  |> movingAverage(n: 10)\n  |> rename(columns: {_value: \"snr_min\"})\n  |> yield(name: \"min\")\n\nrxSnr\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> movingAverage(n: 10)\n  |> rename(columns: {_value: \"snr_max\"})\n  |> yield(name: \"max\")"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "import \"experimental/array\"\n\nbattery = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery\")\n  |> filter(fn: (r) => r[\"_field\"] == \"voltage\")\n  |> filter(fn: (r) => if length(arr: ${gateway:json}) == 0 then true else contains(value: r.gateway_id, set: ${gateway:json}))\n  |> filter(fn: (r) => if length(arr: array.toString(arr: [${nodes::doublequote}])) == 0 then true else contains(value: r._from, set: array.toString(arr: [${nodes::doublequote}])))\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> group(columns: [\"_from\", \"_field\"])\n\nbattery\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 10)"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "battery = from(bucket: \"meshtastic\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"battery\")\n  |> filter(fn: (r) => r[\"_field\"] == \"battery_level\")\n  |> filter(fn: (r) => if length(arr: ${gateway:json}) == 0 then true else contains(value: r.gateway_id, set: ${gateway:json}))\n  |> filter(fn: (r) => r[\"_from\"] == \"${nodes}\")\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> group(columns: [\"_from\", \"_field\"])\n\nbattery\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> movingAverage(n: 10)"
    }
   ]
  }
 ]
}