name: build

on:
  push:
    tags:
      - '*.*.*'
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  docker:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Extract branch name
        id: extract_branch
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/* ]]; then
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
          elif [[ "${GITHUB_REF}" == refs/pull/* ]]; then
            BRANCH_NAME=$(echo ${GITHUB_REF} | sed 's#refs/pull/##; s#/merge##')
          fi
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Set image tags
        id: set_tags
        run: |
          echo "tags=ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:$BRANCH_NAME" >> $GITHUB_OUTPUT
          if [ "$BRANCH_NAME" == "main" ]; then
            echo "tags=ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:$BRANCH_NAME ghcr.io/${{ github.repository }}:latest" >> $GITHUB_OUTPUT
          fi

      - name: Build image
        id: build_image
        uses: redhat-actions/buildah-build@v2.13
        with:
          image: ghcr.io/${{ github.repository }}
          platforms: linux/amd64
          tags: ${{ steps.set_tags.outputs.tags }}
          containerfiles: ./Containerfile

      - name: Push image
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ steps.build_image.outputs.tags }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: self-hosted
    needs: docker
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy Quadlets
        run: config/deploy.sh
